CREATE TABLE Devices (
	UUID VARCHAR(255) PRIMARY KEY,
	pin VARCHAR(255),
	name VARCHAR(255) UNIQUE
);
CREATE TABLE Sensors (
	ID VARCHAR(255) PRIMARY KEY,
	name VARCHAR(255),
	ownerKey VARCHAR(255),
	FOREIGN KEY(ownerKey) REFERENCES Devices(name)
);
CREATE TABLE Data (
	sensorID VARCHAR(255),
	logged DATETIME DEFAULT CURRENT_TIMESTAMP,
	unit VARCHAR(20),
	val INT DEFAULT 0,
	reference INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	FOREIGN KEY(sensorID) REFERENCES Sensors(ID)
);