ARDMK_DIR = /usr/share/arduino
ARDUINO_DIR = /home/elmo/Downloads/arduino-1.6.6
USER_LIB_PATH = $(PWD)/lib

BOARD_TAG = uno
MONITOR_BAUDRATE = 38400
ARDUINO_LIBS = AltSoftSerial iWRAP

include $(ARDMK_DIR)/Arduino.mk

